name: Dart to DockerHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    #- name: Docker build
      #run: docker build . -f Dockerfile -t rcelebrone/dart-server-api
      
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v1.1.1
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{secrets.DOCKER_USERNAME}}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{secrets.DOCKER_PASSWORD}}
        # Dockerhub secret
        # secrets: ${DOCKER_SECRET}
        # Docker repository to tag the image with
        repository: rcelebrone/dart-crud-api
        
