name: Dart to DockerHub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: docker build . -f Dockerfile -t rcelebrone/dart-server-api
    
    - name: Docker push
      # You may pin to the exact commit or the version.
      # uses: actions-hub/docker@726e89023248c002cf9aadfc8b8364687a3ed25f
      uses: actions-hub/docker@v1.0.0
      with:
        # Docker image (if not the same as repo)
        NAME: rcelebrone/dart-crud-api
        # Docker tag (if want to specify tag)
        TAG: latest
        # Docker username
        DOCKER_USERNAME: ${DOCKER_USERNAME}
        # Docker password
        DOCKER_PASSWORD: ${DOCKER_PASSWORD}
        # Docker registry url
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
